### ISSUE TITLE
LARGE: Terraform IAC for GCP/GKE

### ISSUE THREAD

**Issue by ranchodeluxe** [developmentseed/eoapi-k8s#10]
## Goal:

GKE cluster set up documentation 

## AC

- [X] does GCP/GKE have anything similar to `eksctl` to make the provisioning easier?

**Comment by batpad** [comment]
@ranchodeluxe is there really a benefit to having the IAC stuff to spin up the cluster in this repository? 

Ref: https://github.com/developmentseed/k8s-eoapi/issues/1#issuecomment-1586750152 .

I think I like the idea of having this repository focus on the Helm chart, and have another repository like `k8s-seed` or whatever as a generic way to spin up Kubernetes clusters on different cloud providers.

Of course, the Helm chart may need to take some configuration options to work correctly on different cloud providers - but I'd really like to split up the TF for creating the clusters to a separate thing, that's also generalizable beyond just eoAPI.

@ranchodeluxe do you see any problems with that approach? Do you think we might have very specific requirements for the cluster for eoAPI that means we should do that in this repository?

cc @sunu

**Comment by ranchodeluxe** [comment]
Not sure why these comments are not coming through on my GH gmail threads so sorry about the late reply @batpad. I'm fine with that and what @sunu has done is good enough for now. Let me use his documentation to spin up a cluster in GKE and then plumb through the necessary annotations where needed
