### ISSUE TITLE
Exportable service metrics

### ISSUE THREAD

**Issue by j08lue** [developmentseed/eoapi-k8s#134]
Scope out what it would take to gather service health / usage metrics and make them accessible to any harvester of such metrics, e.g. to feed into a Grafana dashboard or OpenSearch.

Similar to what veda-backend has been doing, e.g.

- https://github.com/NASA-IMPACT/veda-backend/issues/288

Perhaps related to

- #41 

## Acceptance criteria

- [x] Describe possible pathways to an interface that exposes service health and usage metrics / traces

**Comment by j08lue** [comment]
Why this is coming up now:

I learned that the Resource Health building block in EOEPCA will possibly in the future be able to receive OpenTelemetry traces from other building blocks, to ease debugging.

VEDA Backend has set up a centralized usage metrics overview (dashboard), which would also be highly relevant as a feature for eoapi-k8s.

**Comment by ranchodeluxe** [comment]
I think we have about 75% of this already done in `main` b/c our metrics are already exportable via Prometheus on an API endpoint (that's how we have custom metrics about each service to autoscale by) and they get fed to Grafana. If I understand correctly the only addition here would be setting up an ETOL deployment that feeds more data into Prometheus.

That said we use ETOL on the fire atlas stuff and without writing custom metrics I haven't seen a lot of good data coming out of it that we can't get from other metrics APIs already. So something to think about

**Comment by j08lue** [comment]
Great to hear the infrastructure is basically already there and we just need to add some custom metrics.

Let us see once our services are up, which metrics that could be.

What is ETOL? 🙏

**Comment by ranchodeluxe** [comment]
> What is ETOL? 🙏

The Encyclopedia of Trotskyism Online 😉 I mean OTeL

**Comment by ranchodeluxe** [comment]
@j08lue: It also occurred to me this means we'd have to build our own custom runtimes to add OTeL stuff 😞 I really, truly feel like this is yet another example of something that should be plumbed through and turned on in all the upstream libraries 😬

**Comment by j08lue** [comment]
> I think we have about 75% of this already done in main b/c our metrics are already exportable via Prometheus on an API endpoint

We are now planning on including OpenTelemetry in our EOEPCA runtimes and have them feed into Prometheus. From there they can get exposed via Grafana or picked up by external observability services.

We should document the approach EOEPCA takes for other users of eoapi-k8s to follow.

We will discuss in the context of EOEPCA, which additional metrics (besides liveliness / uptime) we would like to gather.

- https://github.com/EOEPCA/data-access/issues/114
