### ISSUE TITLE
Installing eoapi-support Chart On EOEPCA+ Next Steps

### ISSUE THREAD

**Issue by ranchodeluxe** [developmentseed/eoapi-k8s#154]
I didn't get to this in the last few days so just writing down what the issue was and how to problem solve it

#### Problem description

[Prior art Slack message](https://eoepca.slack.com/archives/CQ4MK4B9T/p1726846766257149)

EOEPCA+ has decided to be extra secure and is using a custom certificate authority for all communication within the cluster. Previously when we deployed `eoapi-support` the metrics-server was never able to be fulling deployed for this reason. It basically wasn't able to communicate with the `kubelet` on the nodes b/c of an SSL error and that prevented other namespaces from being deleted.

The internal CA issuer is called `eoepca-ca-clusterissuer`

Tilo Wiklund pointed me to this example using it: https://github.com/EOEPCA/eoepca-plus/blob/deploy-develop/argocd/eoepca/resource-health/certificates/opensearch-admin-certificate.yaml

#### Expected Output

`metrics-server` installs correctly and doesn't hang

#### Next Steps

1. Given that the issue is at the `metrics-server` install no reason to install `eoapi-support` yet (all the other deps seem to work fine).

2. Get access to the RKE cluster via your `kubeconfig` parameters. 

3. Then iterate via manual `helm install metrics-server` with the appropriate value overrides. For example, it looks like we can probably get the existing issuer's CA bundle from k8s cluster and then manually (carefully 😉) add it the [metrics-server values](https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/values.yaml#L47) and try to deploy it that way

4. iterate and profit

**Comment by ividito** [comment]
Seems to be fixed by adding a cert-manager annotation and `insecureSkipTLSVerify: false` - https://github.com/EOEPCA/eoepca-plus/commit/4c81216cb079153db908c91856d363c7142afe80#diff-4181e5df345a16a78ae30ecb707523c1341cd8ff652b9866f8dfe4f5d4a6475aR47
