### ISSUE TITLE
Add healthchecks for the services

### ISSUE THREAD

**Issue by sunu** [developmentseed/eoapi-k8s#26]
#### Problem description
While running the `vector` service through the helm chart, it failed to startup with the following error:
```
 .... <snip></snip> ....
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "s00pers3cr3t"

ERROR:    Application startup failed. Exiting.
```
This error should ideally kill the parent `uvicorn` process but it doesn't. It was still running:
```
root@vector-695c469fbd-qfxlg:/tmp# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.3  31056 26228 ?        Ss   14:52   0:00 /usr/local/bin/python /usr/local/bin/uvicorn tipg.main:
```

We don't have any explicit liveness probes either. So to kubernetes the pod appears healthy:
```
$ kubectl get pods -n eoapi | grep vector
vector-695c469fbd-qfxlg                     1/1     Running   0          22m
```

#### Expected Output

The pod's liveness probe/ startup probe should fail and kubernetes should know that the pod failed to start or has died.

**Comment by ranchodeluxe** [comment]
I've added this for `/vector`, `/raster/`, `/stac` services. I had for `/pgstac` too but removed it b/c the damn `minikube` tests weren't liking it. We can add that back in once I move CI/CD unittests over to use GCP
