### ISSUE TITLE
Install Prometheus and Grafana with eoAPI

### ISSUE THREAD

**Issue by ranchodeluxe** [developmentseed/eoapi-k8s#42]
### Background
To do HPA/VPA properly we need metrics and Prometheus seems to be the best game in town. We also need to visualize metrics to understand whats happening with resourcing in the clstuer. Grafana seems to be the most used open-source project for this.

While these two packages can easily be `helm` installed the main purpose of this ticket is to help users get started quick with docs and other things below

AC:
- [ ] write some documentation about how users of `eoapi-k8s` can install Prometheus and Grafana
- [ ]  is there someway we can export a set of basic Grafana starter graphs?
- [ ] we'll want this as a separate chart just like [2i2c does for these "dependency" patterns](https://github.com/2i2c-org/infrastructure/tree/master/helm-charts/support)

**Comment by Rub21** [comment]
>  is there someway we can export a set of basic Grafana starter graphs?

@ranchodeluxe , Regarding your statement, are you suggesting that we should export the charts as PNG images?  there is this [grafana-image-renderer](https://grafana.com/grafana/plugins/grafana-image-renderer/) that we may need to install in the cluster to export the images, 

Alternatively, if you're referring to exporting the chart data, it can be downloaded as a CSV file.
![image](https://github.com/developmentseed/eoapi-k8s/assets/1152236/5266f8a1-064e-4981-822a-723f92ecfb81)

**Comment by ranchodeluxe** [comment]
> > is there someway we can export a set of basic Grafana starter graphs?
> 
> @ranchodeluxe , Regarding your statement, are you suggesting that we should export the charts as PNG images? there is this [grafana-image-renderer](https://grafana.com/grafana/plugins/grafana-image-renderer/) that we may need to install in the cluster to export the images

Nice work @Rub21 🥳 

Grafana allows us to export dashboards as JSON so they can be imported by downstream users. I've been building a basic set of eoAPI dashboards that actually helped me last week diagnose that our stac pods were being throttled and killed b/c they were running into CPU limits. So I can handle this second AC item. Let me leave a separate comment below on your AC 1&3 stuff. 

![Screen Shot 2023-09-19 at 12 34 11 PM (1)](https://github.com/developmentseed/eoapi-k8s/assets/208859/12a8e7bc-364d-4091-9062-92654a093d59)

**Comment by ranchodeluxe** [comment]
> > [ ]  write some documentation about how users of `eoapi-k8s` can install Prometheus and Grafana
> 
> ## Updates
> ### Prometheus:
> 
> Prometheus is a monitoring tool that helps you keep track of various metrics and statistics for your computer systems, applications, and services. It collects data over time(stores 15days), allowing you to analyze performance, troubleshoot issues.
> ### Exporters: https://prometheus.io/docs/instrumenting/exporters/

This is a great start @Rub21 💯  A couple comments.

* For AC 1 can you move your documentation into a Markdown file into the `/docs` folder please and add a link to the README TOC (in the future we'll probably want to render a whole GH pages but this is fine for now)

* Not sure we really need a separate repo with a bash script that calls `helm install` to add these things. If you look at the link in AC 3 it shows how JH does similar things in the same repo. `helm` can have deps and that makes more sense. Are you comfortable mimicing that? Or we can jam on it together if needed?  Let me know
