### ISSUE TITLE
General Next Steps And Enhancements to Prioritize

### ISSUE THREAD

**Issue by ranchodeluxe** [developmentseed/eoapi-k8s#78]
This repository hasn't really been touched since November and needs some love. Here is my priority list for us to talk about and ticket further with @j08lue and @ividito:

0. Write IaC and documentation about using cloud provider storage solutions (RDS and GCD):
    - add optionally-enabled cloud provider storage to [Terraform](https://github.com/developmentseed/eoapi-k8s-terraform/)
    - documentation [is already started here](https://github.com/developmentseed/eoapi-k8s/pull/44) but needs to be totally redone
    - make sure service charts and configs take `extraSecret` and `extraConfig` to be mounted into the pods like [JH does](https://z2jh.jupyter.org/en/stable/administrator/advanced.html#hub-extraconfig) for `extra*` things
    - relevant to https://github.com/developmentseed/eoapi-k8s/discussions/65#discussioncomment-9447443
  
  
2. It's typical for most demo k8s installs to default to using an in-memory database but I think our default should just install [Crunchy's Postgres Operator ](https://github.com/developmentseed/eoapi-k8s/issues/77). Then folks have high-available k8s alternative already set up to go

4. move CI/CD tests to using k3's. Even though we currently can have parallel tests deploy parallel eoapi-k8s and run against a real cloud provider k3's would be more reliable and just use the CI runners

5. We need to automate releases using GH Actions for releases:

   - releases should also auto-generate a documentation site on GH pages 

7. The[ support helm chart](https://github.com/developmentseed/eoapi-k8s/tree/main/helm-chart/eoapi-support) is crucial to set up Prometheus and certain auto-scaling and needs to be it's own separate chart release:

   - we need to make sure by default this seamlessly gives us the Grafana dashboard and ability [to auto-scale by request](https://github.com/developmentseed/eoapi-k8s/blob/main/docs/autoscaling.md#install-newest-eoapi-chart)

8. Write documentation about generating certs for TLS using Let'sEncrypt. There are manual steps for this like running let's encrypt CLI and generating secrets. The current [helm addition PR also](https://github.com/developmentseed/eoapi-k8s/pull/60) conflates the idea of staging and prod

**Comment by ranchodeluxe** [comment]
Finally got around to ticketing these: 

1. https://github.com/developmentseed/eoapi-k8s/issues/77
2. https://github.com/developmentseed/eoapi-k8s/issues/80
3. https://github.com/developmentseed/eoapi-k8s/issues/39
4. https://github.com/developmentseed/eoapi-k8s/issues/81

@ividito: let me know which ones you're interested in and we can start jamming on them

**Comment by ividito** [comment]
I can pick up 2 and 3 - possibly overlapping with 4, if we start expanding on the `eoapi-support` CI.
